### ISSUE TITLE
Replication Error: cannot install ecapture

### ISSUE THREAD

**Issue by C0derTang** [mmirthula02/AI-Personal-Voice-assistant-using-Python#19]
When I attempt `pip install ecapture` It spits out this error:  
ERROR: Failed building wheel for scikit-image
Failed to build scikit-image
ERROR: Could not build wheels for scikit-image which use PEP 517 and cannot be installed directly

No idea why it's happening. Can you help?

**Comment by Nihu15** [comment]
I had the same error.
Try this command.
`pip install ecapture==0.0.7`
I hope it helps.

**Comment by C0derTang** [comment]
I used  `pip3 install ecapture --no-binary :all:` and solved it, forgot to close the issue. but thanks anyway.
