### ISSUE TITLE
pyaudio is not supported in newer version of python

### ISSUE THREAD

**Issue by jewebb4911** [mmirthula02/AI-Personal-Voice-assistant-using-Python#3]
is there an alternative i can use in place of pyaudio?

**Comment by Rajvir750** [comment]
Yup same with me i also tried to get it from unofficial python binary website but it not work!!

**Comment by RajvirSingh1313** [comment]
I had find a way to solve this problem
[find it here](https://www.youtube.com/watch?v=-3am_5jMzJ4&t)

**Comment by Ghack9** [comment]
You Can Install the Previous version of python i.e. 3.6  because there are many modules that are still not supported in python 3.8.
